### ISSUE TITLE
Spanish Translation

### ISSUE THREAD

**Issue by MarcoLG** [BuggleInc/PLM#460]
Hello, I am a programing Peruvian teacher and I would like to know if there is any incoming  spanish translation ?

**Comment by mquinson** [comment]
Dear Marco,

there is no existing translation to Spanish, but your work would be very welcome ! 

The translation process is described on this page:
https://github.com/BuggleInc/PLM/wiki/Working-on-translations#missions-translation-quick-guide
I think that it explains anything you need to know. If it's not the case, please come back to us so that we can answer your questions and improve that page.

As noted on this page, you should focus on translating the mission texts and the web interface. Translating the Java interface is not really advised as we do not envision any future work on that version. Note that if you translate the Java interface anyway (eg because that's the version you need with your students), we will probably do future releases to integrate it. But the new exercises/universes will go in webPLM.

Thanks for volunteering!
Mt.

**Comment by mquinson** [comment]
Hello Marco,

if you want to help us translating PLM to spanish, you may want to use zanata:
https://translate.zanata.org/iteration/view/plm/missions/languages/fr?dswid=-1846

We are currently experimenting with this system, and I think we will use it in the future.

Feel free to help us.

**Comment by mquinson** [comment]
Actually, we don't have a spanish translation incoming since we do not speak spanish ourselves. We'd need the help of some volunteer for that. I'm closing this bug since there is nothing we can do ourselves.
